name: Deploy to Itch.io

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Upload to Itch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Packages
        run: npm run build

      - name: Download Butler
        run: |
          mkdir -p ~/bin
          curl -L -o ~/bin/butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          (cd ~/bin && unzip butler.zip)
          chmod +x ~/bin/butler

      - name: Push to Itch.io
        run: ~/bin/butler push "$PACKAGE" $ITCH_USER/$ITCH_GAME:$CHANNEL
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html5
          ITCH_GAME: milk-prophecy
          ITCH_USER: bn-jc
          PACKAGE: dist